### ISSUE TITLE
Reflection 1

### ISSUE THREAD

**Issue by Cortesj** [Berea-CS-Courses/capstone-project-Cortesj#16]

**Comment by jazzij** [comment]
This Reflection is ok, and your goals seems reasonable and manageable. It could be more detailed and exact, for example, a list of all the sensors that you planned to test the connectivity for. 
Based on the report out (4/15) the UI reformatting seemed to be very low priority and not really a goal that you actually planned to do. We will be using these documents to track your progress throughout the semester, so think carefully about what you actually plan and can complete. It's tough to estimate, but its a good practice to try.

**Comment by jazzij** [comment]
I also don't see an issue or Pull request related to this database update. Can you show your progress? You don't need to add your database to your repository, but please give us an updated E-R diagram, the representation of the tables and SQL in python, and any scripts you've written so far
