### ISSUE TITLE
Database - Create Entry

### ISSUE THREAD

**Issue by Cortesj** [Berea-CS-Courses/capstone-project-Cortesj#23]
Implement a function to insert a new inventory record and implement a check for all required parameters for the function.

**Comment by jazzij** [comment]
Is this where you create an database entry?
What does temperature and humidity parameters? Are those the target temp and humidity?
https://github.com/Berea-CS-Courses/capstone-project-Cortesj/blob/cd1ae2c1b807733739572be5a4ff35f130d1f609/code/database.py#L33
