### ISSUE TITLE
Database - Delete/Archive Inventory record

### ISSUE THREAD

**Issue by Cortesj** [Berea-CS-Courses/capstone-project-Cortesj#26]
Create the function the would remove a record or archive the record so it doesn't appear on the view inventory without a flag. The archive idea is something that could be useful if you don't want to remove the record itself.

**Comment by jazzij** [comment]
An easy (or easier) way to implement an archive is to create an Archive table in your database that has identical column names to the source table. When the user clicks "Archive" then the record just gets moved to the this table. This will make it easy to show a list of archived items and also easier to delete items if the user decides they no longer need the archived record.
