### ISSUE TITLE
Database - Arduino Sensor Data parser

### ISSUE THREAD

**Issue by Cortesj** [Berea-CS-Courses/capstone-project-Cortesj#27]
Implement a function to parse through current sensor data for the week so it can be saved as a data frame then passed to the appropriate graphic figure.

**Comment by jazzij** [comment]
Why is there a sensor data table and also an inventory data table? Are these connected? 
How are these populated via your database.py?

**Comment by jazzij** [comment]
https://pythonspot.com/orm-with-sqlalchemy/
